name: Build and Deploy to Kubernetes

on:
  push:
    branches:
      - main
  workflow_dispatch:    

env:
  IMAGE_NAME: angular-frontend

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Azure Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/$IMAGE_NAME:latest frontend
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/$IMAGE_NAME:latest

      - name: Configure kubectl (token-based)
        run: |
          kubectl config set-cluster k8s \
            --server=${{ secrets.K8S_SERVER }} \
            --insecure-skip-tls-verify=true

          kubectl config set-credentials github \
            --token=${{ secrets.K8S_TOKEN }}

          kubectl config set-context github \
            --cluster=k8s \
            --user=github \
            --namespace=${{ secrets.K8S_NAMESPACE }}

          kubectl config use-context github

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/
